Create stAgEurRateProvider.md
threerocks-defi/code-review pull request #26
Opened 2023-10-11 16:01 UTC by mkflow27

For: https://github.com/threerocks-defi/code-review/issues/25

Outstanding:
- [x] Update registry
- [x] remove duplicate file

2023-10-11 19:09 UTC, rabmarut requested changes
Thanks, @mkflow27! I added a few inline comments/suggestions and included myself as the checker.

One more thing: all review PRs should also update the [registry](https://github.com/threerocks-defi/code-review/blob/main/rate-providers/registry.json). Can you include those changes too, or let me know if you need guidance on that?

2023-10-11 19:09 UTC, rabmarut commented on stAgEurRateProvider.md
> +    - The `asset` (agEUR) is upgradeable as well by the same 4/6 Multisig.
I think we should list both upgradeable components by contract address here (rather than simply naming `agEUR`).
```suggestion
    - upgradeable component: `stEUR` ([gnosis:0x004626A008B1aCdC4c74ab51644093b155e59A23](https://gnosisscan.io/address/0x004626a008b1acdc4c74ab51644093b155e59a23))
        - admin address: [gnosis:0x0F70EeD1Bb51d5eDB1a2E46142638df959bAFD69](https://gnosisscan.io/address/0x0f70eed1bb51d5edb1a2e46142638df959bafd69)
        - admin type: Multisig 
            - multisig threshold/signers: 4/6
    - upgradeable component: `agEUR` ([gnosis:0x4b1E2c2762667331Bc91648052F646d1b0d35984](https://gnosisscan.io/address/0x4b1e2c2762667331bc91648052f646d1b0d35984))
        - admin: same 4/6 multisig as above
```

2023-10-11 19:09 UTC, rabmarut commented on stAgEurRateProvider.md
> +The rateProvider can be used in production. While the entity who has upgrading power is a 4/6 Multisig, an additional Timelock could protect users additionally from malicious admin power.
I would also add a brief warning to this conclusion section about the 18 decimal issue described above.

2023-10-11 19:09 UTC, rabmarut commented on stAgEurRateProvider.md
> +- Checked by: @\<GitHub handle of secondary reviewer\>
```suggestion
- Checked by: @rabmarut
```

2023-10-11 19:27 UTC, mkflow27 commented on stAgEurRateProvider.md
> +The rate the rateProvider supplies is a function of `totalSupply` of the ERC4626 Vault, which is being influenced bei shares being `mint`ed & `burn`ed - **NOT** by a `balanceOf` function. A flashLoan
I tried to say that I have not verified if large mints/burns could change the exchange Rate between shares/assets. This comment might sound more alarming than it is, yes. Maybe I should add it to the conclusion that this scenario was not checked. What do you think? 

The scenario I had in mind was someone potentially trying to for example
1. Flashloan
2. mint shares and potentially changing exchange rate between shares/assets
3. interact with the pool where the RateProvider is used
4. redeem
5. Pay back flashloan.

However this depends on the possibility of influencing exchange rate between shares/assets which I have not verified and probably is not the case.

2023-10-12 02:28 UTC, baileyspraggins commented on stAgEurRateProvider.md
> +The rate the rateProvider supplies is a function of `totalSupply` of the ERC4626 Vault, which is being influenced bei shares being `mint`ed & `burn`ed - **NOT** by a `balanceOf` function. A flashLoan
When you say Flashloan and mint shares what exactly are you referring to? Borrowing underlying and depositing into the `ERC4626` vault to mint shares of the wrapped asset? 

If so, there is no issue with this and the rate would be accurate. In donation attacks the manipulation occurs from changing the price by donating underlying tokens to the vault contract without minting new wrapped tokens.

2023-10-12 07:28 UTC, mkflow27 commented on stAgEurRateProvider.md
> +The rate the rateProvider supplies is a function of `totalSupply` of the ERC4626 Vault, which is being influenced bei shares being `mint`ed & `burn`ed - **NOT** by a `balanceOf` function. A flashLoan
I have removed this part and only left in the `balanceOf` component. All the changes are reflected in the `stAgEurRateProvider.md` file in the `rate-providers` folder.

2023-10-12 07:29 UTC, mkflow27 commented on stAgEurRateProvider.md
> +The rateProvider can be used in production. While the entity who has upgrading power is a 4/6 Multisig, an additional Timelock could protect users additionally from malicious admin power.
All the changes are reflected in the stAgEurRateProvider.md file in the rate-providers folder.

2023-10-12 07:29 UTC, mkflow27 commented on stAgEurRateProvider.md
> +    - The `asset` (agEUR) is upgradeable as well by the same 4/6 Multisig.
All the changes are reflected in the stAgEurRateProvider.md file in the rate-providers folder.

2023-10-12 14:29 UTC, rabmarut requested changes
Just a couple more minor changes!

2023-10-12 14:29 UTC, rabmarut commented on rate-providers/registry.json
> +            "warnings": ["donation", "decimals"],
I'd suggest two small changes here:
1. Break the array into multiple lines
2. Call the warning `only18decimals` to be a bit clearer about the specific risk
```suggestion
            "warnings": [
                "donation",
                "only18decimals"
            ],
```

2023-10-12 14:29 UTC, rabmarut commented on rate-providers/stAgEurRateProvider.md
> +            - multisig threshold/signers: 4/6
I forgot to add explicit timelock info earlier
```suggestion
            - multisig threshold/signers: 4/6
            - multisig timelock? NO
```

2023-10-12 14:54 UTC, rabmarut requested changes
Whoops, I missed a few things on the previous pass. I think these are the final changes.

2023-10-12 14:54 UTC, rabmarut commented on rate-providers/stAgEurRateProvider.md
> +
We should keep the unchecked items from the template as well so that it's clear we reviewed these things.

```suggestion
### Administrative Privileges
- [ ] The Rate Provider is upgradeable (e.g., via a proxy architecture or an `onlyOwner` function that updates the price source address).

```

2023-10-12 14:54 UTC, rabmarut commented on rate-providers/stAgEurRateProvider.md
> +### Oracles
```suggestion
### Oracles
- [ ] Price data is provided by an off-chain source (e.g., a Chainlink oracle, a multisig, or a network of nodes).
- [ ] Price data is expected to be volatile (e.g., because it represents an open market price instead of a (mostly) monotonically increasing price).
```

2023-10-12 14:54 UTC, rabmarut commented on rate-providers/stAgEurRateProvider.md
> +
Let's also keep this text from the template.
```suggestion
## Additional Findings
To save time, we do not bother pointing out low-severity/informational issues or gas optimizations (unless the gas usage is particularly egregious). Instead, we focus only on high- and medium-severity findings which materially impact the contract's functionality and could harm users.

- N/A
```

2023-10-12 14:54 UTC, rabmarut commented on rate-providers/stAgEurRateProvider.md
> +    - [\<audit title\>](\<link to audit\>)
```suggestion
    - [Angle Protocol Audits](https://docs.angle.money/resources/audits)
```

2023-10-12 16:26 UTC, rabmarut approved these changes

2023-10-12 16:37 UTC, merged