review: TruMaticRateProvider
threerocks-defi/code-review pull request #32
Opened 2023-10-16 14:25 UTC by mkflow27

Closes: https://github.com/threerocks-defi/code-review/issues/30
Tasks outstanding:
- [x] add registry entry
- [x] add summary judgement 
- [x] determine admin type
- [x] Investigate potential offchain component

2023-10-18 23:42 UTC, rabmarut requested changes

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/TruMaticRateProvider.md
> +        - trustworthy signers? NO
Let's adopt the more recent standard where we also point out the implementation that we reviewed. (We will have to add this to the template later.)
```suggestion
    - upgradeable component: `TruMATIC`
        - entry point: ([ethereum:0xA43A7c62D56dF036C187E1966c03E2799d8987ed](https://etherscan.io/address/0xA43A7c62D56dF036C187E1966c03E2799d8987ed))
        - implementation reviewed: ([ethereum:0x2a9fD373Ed3Ce392bb5ad8Ee146CFAB66c9fAEae](https://etherscan.io/address/0x2a9fd373ed3ce392bb5ad8ee146cfab66c9faeae#code))
        - admin address: [ethereum:0x71598A2209b4a9C3E23260Ac373180f4B637136d](https://etherscan.io/address/0x71598A2209b4a9C3E23260Ac373180f4B637136d)
        - admin type: multisig
            - multisig threshold/signers: 5/7
            - multisig timelock? NO
            - trustworthy signers? NO
    - upgradeable component: `ValidatorShare`
        - entry point: ([ethereum:0xeA077b10A0eD33e4F68Edb2655C18FDA38F84712](https://etherscan.io/address/0xeA077b10A0eD33e4F68Edb2655C18FDA38F84712))
        - implementation reviewed: ([ethereum:0xf98864DA30a5bd657B13e70A57f5718aBf7BAB31](https://etherscan.io/address/0xf98864da30a5bd657b13e70a57f5718abf7bab31#code))
        - admin address: [ethereum:0xFa7D2a996aC6350f4b56C043112Da0366a59b74c](https://etherscan.io/address/0xFa7D2a996aC6350f4b56C043112Da0366a59b74c#code)
        - admin type: multisig
            - multisig threshold/signers: 5/9
            - multisig timelock? YES: 2 days
            - trustworthy signers? NO
```

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/TruMaticRateProvider.md
> +        - trustworthy signers? NO
Let's adopt the more recent standard where we also point out the implementation that we reviewed. (We will have to add this to the template later.)

```suggestion
- [x] The Rate Provider is upgradeable (e.g., via a proxy architecture or an `onlyOwner` function that updates the price source address).
    - implementation reviewed: [ethereum:0x6e8135b003F288aA4009D948e9646588861C5575](https://etherscan.io/address/0x6e8135b003f288aa4009d948e9646588861c5575#code)
    - admin address: [ethereum:0x71598A2209b4a9C3E23260Ac373180f4B637136d](https://etherscan.io/address/0x71598A2209b4a9C3E23260Ac373180f4B637136d)
    - admin type: multisig
        - multisig threshold/signers: 5/7
        - multisig timelock? NO
        - trustworthy signers? NO
```

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/TruMaticRateProvider.md
> +- [x] Some other portion of the price pipeline is upgradeable (e.g., the token itself, an oracle, or some piece of a larger system that tracks the price). \<Delete this hint: If unchecked, delete all
```suggestion
- [x] Some other portion of the price pipeline is upgradeable (e.g., the token itself, an oracle, or some piece of a larger system that tracks the price).
```

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/TruMaticRateProvider.md
> +
I observed that the `ValidatorShare#getTotalStake()` function calls into the `StakeManager` contract, which is also upgradeable.

```suggestion
    - upgradeable component: `StakeManager`
        - entry point: ([ethereum:0x5e3Ef299fDDf15eAa0432E6e66473ace8c13D908](https://etherscan.io/address/0x5e3Ef299fDDf15eAa0432E6e66473ace8c13D908))
        - implementation reviewed: ([ethereum:0xbA9Ac3C9983a3e967f0f387c75cCbD38Ad484963](https://etherscan.io/address/0xba9ac3c9983a3e967f0f387c75ccbd38ad484963#code))
        - admin address: [ethereum:0xFa7D2a996aC6350f4b56C043112Da0366a59b74c](https://etherscan.io/address/0xFa7D2a996aC6350f4b56C043112Da0366a59b74c#code)
        - admin type: multisig
            - multisig threshold/signers: 5/9
            - multisig timelock? YES: 2 days
            - trustworthy signers? NO
https://etherscan.io/address/0x5e3Ef299fDDf15eAa0432E6e66473ace8c13D908#readProxyContract

```

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/TruMaticRateProvider.md
> +    }
```suggestion
function totalAssets() public view virtual override returns (uint256) {
    return _asset.balanceOf(address(this));
}
```

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/TruMaticRateProvider.md
> +- [ ] Price data is provided by an off-chain source (e.g., a Chainlink oracle, a multisig, or a network of nodes).
@mkflow27 It seems to me like there is off-chain data included in this pipeline. Please investigate the source of `TruStakeMATICv2#totalStaked()`, which is included in the price calculation. (This function calls into `VaildatorShare` which further calls into `StakeManager`.)

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/registry.json
> +        "0xc7177B6E18c1Abd725F5b75792e5F7A3bA5DBC2c": {
```suggestion
        "0x4b697C8c3220FcBdd02DFFa46db5a896ae7a0843": {
```

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/registry.json
> +                {
We should include the rate provider itself since that's upgradeable.
```suggestion
                {
                    "entrypoint": "0x4b697C8c3220FcBdd02DFFa46db5a896ae7a0843",
                    "implementationReviewed": "0x6e8135b003F288aA4009D948e9646588861C5575"
                },
```

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/registry.json
> +                }
Also include `StakeManager`.
```suggestion
                },
                {
                    "entrypoint": "0x5e3Ef299fDDf15eAa0432E6e66473ace8c13D908",
                    "implementationReviewed": "0xbA9Ac3C9983a3e967f0f387c75cCbD38Ad484963"
                }
```

2023-10-18 23:42 UTC, rabmarut commented on rate-providers/TruMaticRateProvider.md
> +- Checked by: @\<GitHub handle of secondary reviewer\>
```suggestion
- Checked by: @rabmaurt
```

2023-10-19 10:01 UTC, mkflow27 commented on rate-providers/TruMaticRateProvider.md
> +- [ ] Price data is provided by an off-chain source (e.g., a Chainlink oracle, a multisig, or a network of nodes).
The `delegatedAmount` of the `validatorId` (148) is being read. This validator has been investigated before and is: https://etherscan.io/address/0xeA077b10A0eD33e4F68Edb2655C18FDA38F84712.

TruStakeMATICv2.totalStaked() -> ValidatorShare.getTotalStake(TruStakeMATICv2). the shares computed as part of getTotalStake(TruStakeMATICv2) are an ERC20 balance.
Additionally a `rate` is computed via `exchangeRate()`. The potentially relevant call is:
`stakeManager.delegatedAmount(148)`. 

This function reads from a `Validator` from a `validators` mapping and accesses the `delegatedAmount`. 

Let's collectively dig deeper here, please. Could we agree on a time during our stand up.

2023-10-20 13:10 UTC, rabmarut approved these changes

2023-10-23 09:55 UTC, merged